### ISSUE TITLE
Updating exceptions to reflect recent changes to fused-effects

### ISSUE THREAD

**Issue by riz0id** [fused-effects/fused-effects-exceptions#14]
Since fused-effects is no longer using instances of `Effect` or `HFunctor` may I revise exceptions [here](https://github.com/fused-effects/fused-effects-exceptions/blob/82abf48863720c3aee74f9e627866dc9b6941ddf/src/Control/Carrier/State/IORef.hs#L65) to reflect those changes made in fused-effects pulls [#361](https://github.com/fused-effects/fused-effects/pull/361) and [#359](https://github.com/fused-effects/fused-effects/pull/359)?

**Comment by robrix** [comment]
@riz0id sorry for the late response! That would have been lovely, and I’m very appreciative of the kind offer, but as it turns out that’s the next thing blocking the thing I’m working on right now, so I’ve got it covered. I’ll close this issue out now as a result.

(As an aside: going forward, I think PRs are generally welcome, but issues like this are a great idea in particular when the changes you have in mind are particularly large.)

Thanks again! ❤️
